ECE\Bundle\AuthBundle\Entity\People:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            length: 255
        pass:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
